### ISSUE TITLE
Use DynamoDB streams

### ISSUE THREAD

**Issue by ImaduddinAMajid** [ImaduddinAMajid/emptor-trial-project#33]
## The Story
As a Software Engineer,
I want to use DynamoDB streams instead of Lambda invocation,
so that we can keep data in-sync.

## Problem
Currently we use explicit function invocation.

## Proposal
change `serverless.yml` to use DynamoDB stream 

## Acceptance Criteria
- [ ] Use DynamoDB stream to invoke processing lambda function

**Comment by ImaduddinAMajid** [comment]
![image](https://user-images.githubusercontent.com/16607741/58744847-e70ab700-8450-11e9-9edb-d4aea1b2d6a1.png)
```
    events:
      - stream:
         type: dynamodb
         batchSize: 1
         startingPosition: LATEST
         arn:
           Fn::GetAtt:
             - TitleDynamoTable
             - StreamArn
```
